### PR TITLE
Added Protean transformer

### PR DESCRIPTION
**Pull request by blanu**
This is a transformer that combines the other transformers.
Currently it just combines the AES encryption and the byte sequence injector.
This branch also contains a minor fix for ByteSequenceShaper and some formatting fixes.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/284)

### CODE REVIEW

**Comment by jpevarnek** [comment]
Hey, so, I pretty much just looked at style stuff here, so you probably should not consider this sufficient for merging.

Overall comment: there is a lot of inconsistency between doing `var :Type` and `var:Type`.  I'm reasonably sure both versions are allowed by our style guide (read: I could not find anything prohibiting either version in our style guide when I was looking yesterday) but we should try to stick with just one.  FWIW, the overall team seems to prefer `var :Type`.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[src/churn/churn.ts, line 319 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyxx1bYtS_j1ISn1LIh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L319)):</sup>
This looks like it is getting the entire config, possibly rename to `makeSampleEncryptionConfig_` or `getSampleEncryptionConfig_`?

---

<sup>**[src/churn/churn.ts, line 322 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyxxFiRNnZ71MVCQrgq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L322)):</sup>
The closing brace there is a bit odd readability-wise.  I think you either want to have all this on one line (`{key: (val)}`) or actually split
```
return {
  key: (val)
};
```

---

<sup>**[src/churn/churn.ts, line 339 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyxxwm97T8UFSJ34-N_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L339)):</sup>
Again on it seeming like the function name should mention a config

---

<sup>**[src/churn/churn.ts, line 342 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyxxue2KA0LYT97BDC_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L342)):</sup>
Again on the line ending here being a bit confusing

---

<sup>**[src/fancy-transformers/protean.ts, line 17 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyxzvyB6PTlPxSWEK7S)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/fancy-transformers/protean.ts#L17)):</sup>
`<T, E>`

Also, any chance of renaming `t` to something like `element` (same with better naming for `ys` and `x` below).

---

<sup>**[src/fancy-transformers/protean.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyy-UvTqALEIR2DZYoE)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/fancy-transformers/protean.ts#L36)):</sup>
My instinct here would be that it should throw an exception about not being implemented.  Thoughts on that?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284)

**Comment by blanu** [comment]
The uProxy codebase is highly inconsistent on this I have converted all of the code in the pull request to use var :Type.

---

Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn/churn.ts, line 319 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyxx1bYtS_j1ISn1LIh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L319)):</sup>
Okay I have made this change.

---

<sup>**[src/churn/churn.ts, line 322 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyxxFiRNnZ71MVCQrgq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L322)):</sup>
Feedback from +@trevj in previous code reviews requested both that each field have its own line in a map constructor (I have added this to the style guide) and that closing curly braces for map constructors go at the end of the line instead of the next line (this is not in the style guide). It's possible that these style guidelines are overridden in the special case of there only being one field. In which case, the former single line option seems more consistent than the latter with the closing curly brace on a new line. If so, we should add this to the style guide. I went ahead and made the change to use the single line formatting.

---

<sup>**[src/churn/churn.ts, line 339 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyxxwm97T8UFSJ34-N_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L339)):</sup>
Okay I have made this change.

---

<sup>**[src/churn/churn.ts, line 342 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyxxue2KA0LYT97BDC_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L342)):</sup>
This is definitely the style that +@trevj requested in a previous code review. As the formatting requests are in conflict and this is not specified in the style guide, I am not going to make the requested change at this time. I propose that we should discuss this offline, reach a consensus, and add it to the style guide.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284)

**Comment by blanu** [comment]
Review status: 2 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

<sup>**[src/fancy-transformers/protean.ts, line 17 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyxzvyB6PTlPxSWEK7S)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/fancy-transformers/protean.ts#L17)):</sup>
Okay I have made this change.

---

<sup>**[src/fancy-transformers/protean.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyy-UvTqALEIR2DZYoE)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/fancy-transformers/protean.ts#L36)):</sup>
I have already done this for the other transformers and I just forgot to do it here. I have made this change.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284)

**Comment by jpevarnek** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn/churn.ts, line 322 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyxxFiRNnZ71MVCQrgq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L322)):</sup>
My general instinct when something is not covered in our style guide is to defer to https://google.github.io/styleguide/javascriptguide.xml#Array_and_Object_literals.  Otherwise, just try to make sure that it is relatively simple to understand what you are looking at (when I read that the first time, I had to go back and figure out where the object had actually ended)

---

<sup>**[src/churn/churn.ts, line 342 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-Jyxxue2KA0LYT97BDC_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L342)):</sup>
Okay, in that case, good for now, and let's talk with @trevj offline at some point.  Again, just one of those things that makes parsing the code slower.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284)

**Comment by trevj** [comment]
I love how you've re-used code. Very nice!

:+1:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn/churn.ts, line 321 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyxxFiRNnZ71MVCQrgq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d860802266526a811edffec74cf8951f0acb64fe/src/churn/churn.ts#L321)):</sup>
Apologies for the confusion! Seems like we're all agreed braces in this context should have their own line :-)

---

<sup>**[src/fancy-transformers/protean.ts, line 23 \[r3\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyyNgT1NRfiPj0YGaW9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/b11d37dd8049cbd56aae5d4964f4557750b0c4ea/src/fancy-transformers/protean.ts#L23)):</sup>
And packet injection!

---

<sup>**[src/fancy-transformers/protean.ts, line 23 \[r3\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284#-JyyNhe4CMzsbGyX5zLY)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/b11d37dd8049cbd56aae5d4964f4557750b0c4ea/src/fancy-transformers/protean.ts#L23)):</sup>
Do you plan to add packet length stuff here, too?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/284)

**Pull request merged**
