### PR TITLE
Holographic ICE

### PR DESCRIPTION
**Pull request by bemasc**
Tested between Firefox and Chrome in various NAT configurations.

Fixes https://github.com/uProxy/uproxy/issues/1255

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/208)

### CODE REVIEW

**Comment by trevj** [comment]
Very nice.

FYI, I just tried on my machine and the problems I experienced related to my Docker virtual interfaces are gone. Very cool.

I haven't looked at this in-depth -- right now, I had a couple of suggestions for reducing the amount of signalling messages. We also need to think a tiny bit more about backwards compatibility.

---

Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn/candidate.ts, line 13 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX9aNcCQSxIr2B3TxB)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L13)):</sup>
Some comments would really help here, even if just to link to the RTC, e.g.:
```js
// Represents candidates as described in section 15.1 of the ICE RFC:
//   http://tools.ietf.org/html/rfc5245#section-15.1
```

It would be nice to provide an example candidate line too, e.g.
```
a=candidate:9097 1 udp 4175 127.0.0.1 50840 typ relay raddr 172.26.108.25 rport 56635
```

---

<sup>**[src/churn/candidate.ts, line 18 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX91lOYT1iGvqCQ92u)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L18)):</sup>
It seems like every candidate will have an address and port; perhaps rename these fields to `address` and `port`?

---

<sup>**[src/churn/candidate.ts, line 26 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX9Otc1Kv3gSJR30BT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L26)):</sup>
I wonder if you could get by with just modelling candidate lines?

---

<sup>**[src/churn/candidate.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXBedaA3vJ4CTRpSHT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L29)):</sup>
This returns the publically addressable endpoint?

---

<sup>**[src/churn/candidate.ts, line 90 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXByZP_H0KSp0g9SOC)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L90)):</sup>
naming suggestion: `stringToNumber`

---

<sup>**[src/churn/churn.ts, line 218 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXFm95x1n0uaZTaMOM)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/churn.ts#L218)):</sup>
Could you send multiple `publicEndpoint` signals? They're much more compact than the raw candidate lines.

---

<sup>**[src/churn/churn.ts, line 218 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXJ_mKUKzeYNIAzGn3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/churn.ts#L218)):</sup>
Can you filter out TCP candidates here? Right now, we're sending a lot of unuseable signalling messages.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208)

**Comment by bemasc** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn/candidate.ts, line 13 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX9aNcCQSxIr2B3TxB)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L13)):</sup>
Done.

---

<sup>**[src/churn/candidate.ts, line 18 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX91lOYT1iGvqCQ92u)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L18)):</sup>
OK.  I renamed them to `ip` and `port`, following the latest ORTC nomenclature.

---

<sup>**[src/churn/candidate.ts, line 26 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX9Otc1Kv3gSJR30BT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L26)):</sup>
That would work, but I think it would require four additional mentions of `sdpMid` and `sdpMLineIndex` in churn.ts, so I think this is more convenient overall.

---

<sup>**[src/churn/candidate.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXBedaA3vJ4CTRpSHT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L29)):</sup>
Sometimes.  Added a comment.

---

<sup>**[src/churn/candidate.ts, line 90 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXByZP_H0KSp0g9SOC)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L90)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 218 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXJ_mKUKzeYNIAzGn3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/churn.ts#L218)):</sup>
Already done, see the `if` statement above.

---

<sup>**[src/churn/churn.ts, line 218 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXFm95x1n0uaZTaMOM)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/churn.ts#L218)):</sup>
This would definitely work but it makes me a little uncomfortable.  I feel like the less we get in the way (and the more we preserve things like priority and generation), the more likely WebRTC is to work quickly and well.  We might find that we need `sdpMid` if we want to enable voice and video.

However, switching to a pure `publicEndpoint`-based solution would actually work fine with this code, (no compatibility problem).  That makes me inclined to consider that option later.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208)

**Comment by trevj** [comment]
Agh, sorry I didn't see this yesterday.

I'm getting closer to understanding this -- some suggestions, and we need to think a little about backwards compatibility, viz. `publicEndpoint`.

---

Review status: 0 of 8 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 98 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfQyNdhB5iK4GZwLd3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L98)):</sup>
What are the keys?

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 107 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfY1BZX33Qm1DHFgzo)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L107)):</sup>
I am currently not following the purpose of this field :-)

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 124 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfRbIz7puuUVcS8NLv)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L124)):</sup>
I remember this point being a subtle could-but-probably-won't-trip-us-up-but-would-be-super-hard-to-debug thing.

Probably worth mentioning at the class level instead.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 161 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfSaxQvKEi_PqEoS5a)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L161)):</sup>
Clearly, this function is clearly *super confusingly* named!

A TODO to rename it is fine for now.

---

<sup>**[src/churn/candidate.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX9aNcCQSxIr2B3TxB)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L23)):</sup>
Thanks.

---

<sup>**[src/churn/candidate.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX91lOYT1iGvqCQ92u)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L28)):</sup>
OK. And `relatedIp`? :-)

Is this type only used by the pipe? I think it might get super annoying to remember which types use `address` and which use `ip`. But if this type is only used here, sure.

---

<sup>**[src/churn/candidate.ts, line 40 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXBedaA3vJ4CTRpSHT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L40)):</sup>
A method-level comment would be better, I think.

---

<sup>**[src/churn/churn.ts, line 66 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfMJNWUoCJZsZcIvHO)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn/churn.ts#L66)):</sup>
Reads a lot better, easier to modify. Neat!

---

<sup>**[src/churn/churn.ts, line 218 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXFm95x1n0uaZTaMOM)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/churn.ts#L218)):</sup>
Agree we should manipulate the lines as little as possible.

In that case, we have a backwards compatibility question. If you know the remote peer is running holographic ICE, there's no need to send `publicEndpoint`. I would suggest adding a constructor argument indicating this support; it will be straightforward to update the UI to set it.

---

<sup>**[src/churn/churn.ts, line 218 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXJ_mKUKzeYNIAzGn3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/churn.ts#L218)):</sup>
Oh, I see. Sorry.

---

<sup>**[src/churn/churn.ts, line 285 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfQ876hpTr3DD1ZSOR)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn/churn.ts#L285)):</sup>
Is `endpoint` the source of a packet received? A comment would help.

---

<sup>**[src/churn/churn.ts, line 290 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfQ4-yoHputdx-uRaJ)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn/churn.ts#L290)):</sup>
So this callback tells us the endpoint of a new "local socket"?

It's not clear why this is received so asynchronously from the calls to `bindLocal`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208)

**Comment by bemasc** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 98 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfQyNdhB5iK4GZwLd3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L98)):</sup>
Added a comment.grun

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 107 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfY1BZX33Qm1DHFgzo)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L107)):</sup>
Done.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 124 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfRbIz7puuUVcS8NLv)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L124)):</sup>
Done.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 161 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfSaxQvKEi_PqEoS5a)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn-pipe/churn-pipe.ts#L161)):</sup>
Done.

---

<sup>**[src/churn/candidate.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX91lOYT1iGvqCQ92u)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L28)):</sup>
Don't blame me.  Blame the working group: http://ortc.org/wp-content/uploads/2015/06/ortc.html#rtcicecandidate*.

`Candidate` is only used by churn.ts (not churn-pipe.ts).

---

<sup>**[src/churn/candidate.ts, line 40 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXBedaA3vJ4CTRpSHT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L40)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 218 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsXFm95x1n0uaZTaMOM)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/churn.ts#L218)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 285 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfQ876hpTr3DD1ZSOR)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn/churn.ts#L285)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 290 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsfQ4-yoHputdx-uRaJ)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/6ca1bc662a8c1ce95aad280a8af7307989559e92/src/churn/churn.ts#L290)):</sup>
Tried to clarify with a comment.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208)

**Comment by trevj** [comment]
Awesome. I think we have some work to do to make the code more readable - imagine trying to understand churn now, looking just at this! - but :+1:. Great work.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[src/churn/candidate.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208#-JsX91lOYT1iGvqCQ92u)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/efaf4622d2905674e41f334ffdb225dedc91b7d7/src/churn/candidate.ts#L28)):</sup>
Okay :-)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/208)

**Pull request merged**
