### PR TITLE
replace arraybuffers hexstring converters with buffer built-ins

### PR DESCRIPTION
**Pull request by trevj**
I have unintentionally waged war against this class. This all in preparation for the upcoming RC4 transformer.

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/396)

### CODE REVIEW

**Comment by mollyling** [comment]
This is a wonderful PR comment.

**Comment by jpevarnek** [comment]
I love this!  I kind of wish we were more standardized with how we're passing data around (hex seems like a bad choice there), but totally fine with this improvement! :thumbsup:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/echo/freedom-module.ts, line 45 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/396#-KGIrgPVzFF_WU1UPgEB:-KGIrgPWJmNSP9x1zFIY:-770767821) ([raw file](https://github.com/uproxy/uproxy-lib/blob/eafec2bbd89ea98746cab0914c83447ede5d8e96/src/echo/freedom-module.ts#L45)):*
It seems like it would be simpler to just compare the actual binary data here, is there a reason we decided to do this in hex?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/uproxy-lib/396#-:-KGIs019WDygGgNEAucQ:-1318606907)*

**Comment by trevj** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/echo/freedom-module.ts, line 45 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/396#-KGIrgPVzFF_WU1UPgEB:-KGJ9OdhC_nXOQH9x7UF:1560293660) ([raw file](https://github.com/uproxy/uproxy-lib/blob/eafec2bbd89ea98746cab0914c83447ede5d8e96/src/echo/freedom-module.ts#L45)):*
No good reason! Fixed, thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/uproxy-lib/396)*

**Comment by jpevarnek** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/uproxy/uproxy-lib/396)*

**Pull request merged**
