### PR TITLE
Fix observed race in PoolChannel

### PR DESCRIPTION
**Pull request by bemasc**
Includes a regression test, and changes to the Gruntfile to
enable the regression test.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/220)

### CODE REVIEW

**Comment by trevj** [comment]
Awesome. I just think we can reduce the complexity of the control message handling code -- we'll be thankful in N months time when we revisit this code :-)

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[src/pool/pool.ts, line 267 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjdMdPDT4AnD-opIz_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L267)):</sup>
This isn't an error condition, so I think `debug` is more appropriate.

---

<sup>**[src/pool/pool.ts, line 271 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-Jtjd8OjedI2b0GBCahn)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L271)):</sup>
These two lines are duplicated code; suggest you factor this out into a function, e.g.:
```typescript
var doOpen = () => {
  log.debug('%1: Changing state from CLOSED to OPEN', this.getLabel());
  this.state_ = State.OPEN;
  this.fulfillOpened_();
}
```

---

<sup>**[src/pool/pool.ts, line 274 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjdRih6TyZ7g0Mr2R_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L274)):</sup>
You're increasing the cyclomatic complexity unnecessarily -- you can avoid the `return` statements by making the `if` at line 280 an `else if`.

---

<sup>**[src/pool/pool.ts, line 297 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjflvlZWuWiOVqg6_p)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L297)):</sup>
You might want to log a warning if it is closed.

---

<sup>**[src/pool/pool.ts, line 306 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjfufATQtq9zDU5jsq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L306)):</sup>
Again, I think you could factor these lines into a `doClose` function, e.g.
```typescript
var doClose = () => {
  if (this.state_ === State.PERMANENTLY_CLOSED) {
    log.warn('%1: data processed, but channel has permanently closed', this.getLabel());
    return;
  }
  log.debug('%1: Changing state to CLOSED', this.getLabel());
  this.state_ = State.CLOSED;
}
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220)

**Comment by bemasc** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[src/pool/pool.ts, line 267 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjdMdPDT4AnD-opIz_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L267)):</sup>
I think it is an error condition.  In fact, I think it is impossible!  We should never get an OPEN message until after both sides have closed.

---

<sup>**[src/pool/pool.ts, line 274 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjdRih6TyZ7g0Mr2R_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L274)):</sup>
Not exactly (the early returns are important), but how about this?

---

<sup>**[src/pool/pool.ts, line 285 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-Jtjd8OjedI2b0GBCahn)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L285)):</sup>
Done.

---

<sup>**[src/pool/pool.ts, line 307 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjflvlZWuWiOVqg6_p)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L307)):</sup>
Done.

---

<sup>**[src/pool/pool.ts, line 318 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjfufATQtq9zDU5jsq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L318)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220)

**Comment by trevj** [comment]
One suggestion you might consider, but :+1:. Yay!

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[src/pool/pool.ts, line 211 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtnXKwOlcJGSFoJNrGz)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/66c9de36a85f9a612cc7dedaf1a453d5655e0c76/src/pool/pool.ts#L211)):</sup>
You might add a function to change state and log, e.g.:
```typescript
private changeState_ = (state:State) : void => {
  log.debug('%1: changing state from %2 to %2', this.getLabel(), State[state], State[this.state_]);
  this.state_ = state;
}
```

---

<sup>**[src/pool/pool.ts, line 281 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjdMdPDT4AnD-opIz_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L281)):</sup>
Got it. So the *real* problem was we weren't unsetting the `dataFromPeerQueue` handler when we receive a close message.

---

<sup>**[src/pool/pool.ts, line 286 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjdRih6TyZ7g0Mr2R_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L286)):</sup>
Much better, thanks.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220)

**Comment by bemasc** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/pool/pool.ts, line 211 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtnXKwOlcJGSFoJNrGz)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/66c9de36a85f9a612cc7dedaf1a453d5655e0c76/src/pool/pool.ts#L211)):</sup>
Done.

---

<sup>**[src/pool/pool.ts, line 281 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220#-JtjdMdPDT4AnD-opIz_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/35cf3d76cb6bc344cab9981ad54c3e6e3483ff50/src/pool/pool.ts#L281)):</sup>
Right, I think that's the real fix here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/220)

**Pull request merged**
