### PR TITLE
Add cleanup and shutdown methods to churn-pipe and the integration tests

### PR DESCRIPTION
**Pull request by bemasc**
Fixes https://github.com/uProxy/uproxy/issues/1674

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/262)

### CODE REVIEW

**Comment by trevj** [comment]
Nice! wish we didn't have to do this module closing business, but nice. Just a few things...

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 454 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0KMKgggpb8L36XOy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L454)):</sup>
I think you want to do this on failure, too.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 463 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq2bkarh2t0SI7BSVy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L463)):</sup>
I thought `Array.prototype.push` returns a number. Does this do what you want it to do?

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 471 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0ad3SENwZvKENrZa)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L471)):</sup>
this is weird, will `mirrorPromise` ever be `undefined`?

---

<sup>**[src/churn/churn.ts, line 461 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0srXA729bHuZ9NSb)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn/churn.ts#L461)):</sup>
Mmm, I think you could write:
```typescript
public close = () : Promise<void> => {
  var promises = [this.obfuscatedConnection_.close()];
  if (this.pipe_) {
    promises.push(this.pipe_.shutdown().then(() => {
      freedom['churnPipe'].close(this.pipe_);
    });
  }
  return Promise.all(promises).then((voids:void[]) : void => {});
}
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262)

**Comment by bemasc** [comment]
Yeah, that would be nice.  I turned it into a suggestion: https://github.com/freedomjs/freedom/issues/295

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 454 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0KMKgggpb8L36XOy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L454)):</sup>
Done.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 463 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq2bkarh2t0SI7BSVy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L463)):</sup>
I think it does, but I've replaced it with a much more readable formulation.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 471 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0ad3SENwZvKENrZa)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L471)):</sup>
You're right, it will not!  `mirrorPromises` is a sparse array, so not all of its elements are defined, but it turns out that `forEach` skips the missing elements entirely!

---

<sup>**[src/churn/churn.ts, line 461 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0srXA729bHuZ9NSb)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn/churn.ts#L461)):</sup>
Done.  I also added a `catch` for the failure case.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262)

**Comment by trevj** [comment]
A couple of easy-to-fix things, then :+1:.

---

Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 454 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0KMKgggpb8L36XOy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L454)):</sup>
Now you're only doing it on failure!

This would work (re-add the log line if you like):

```typescript
private static closeSocket_(socket:Socket) : Promise<void> {
  var f = () => {
    freedom['core.udpsocket'].close(socket);
  };
  return socket.destroy().then(f, f);
}      

```

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 463 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq2bkarh2t0SI7BSVy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L463)):</sup>
Much more readable, thanks!

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 471 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0ad3SENwZvKENrZa)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L471)):</sup>
Awesome :-)

---

<sup>**[src/churn/churn.ts, line 484 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0srXA729bHuZ9NSb)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn/churn.ts#L484)):</sup>
Awesome. Ah, just realised you should probably do the `freedom['churnPipe'].close(this.pipe_);` on success *and* failure, as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262)

**Comment by bemasc** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 456 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0KMKgggpb8L36XOy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L456)):</sup>
I think this pattern works.  Try this at the JS console:
```javascript
var resolve, p = new Promise((F, R) => { resolve = F; });
p.catch(() => { alert('Not executed'); }).then(() => { console.log('Runs anyway'); });
resolve();
```
I'm happy to use your version if you think it would be better code.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262)

**Comment by trevj** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 456 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0KMKgggpb8L36XOy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L456)):</sup>
Don't you want to call ` freedom['core.udpsocket'].close(socket);` whether or not `socket.destroy()` throws? `destroy` has no special meaning to the freedomjs module.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262)

**Comment by bemasc** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 456 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0KMKgggpb8L36XOy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L456)):</sup>
Yes.  The `catch` call discards any possible error, but if there isn't an error but I think it's a no-op/passthrough.  `then` runs either way.  I was trying to prove this with the snippet above.  (Of course, it's possible that I've misunderstood.)

---

<sup>**[src/churn/churn.ts, line 484 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0srXA729bHuZ9NSb)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn/churn.ts#L484)):</sup>
I think this is the same issue as above.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262)

**Comment by trevj** [comment]
Wow, sorry. Your code is good, and you should feel good.

:+1:

---

Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 456 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0KMKgggpb8L36XOy)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn-pipe/churn-pipe.ts#L456)):</sup>
Oh, I am sorry. Yes I think this is right and I much prefer it to what I originally suggested. Many thanks!

---

<sup>**[src/churn/churn.ts, line 484 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262#-Jxq0srXA729bHuZ9NSb)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/495ff80f85b58eaccead0a5bf6725b288ca22aeb/src/churn/churn.ts#L484)):</sup>
Yes, you're exactly right :-)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/262)

**Pull request merged**
