### PR TITLE
Fixed peer connection test

### PR DESCRIPTION
**Pull request by iislucas**
* Added mock event handler
* Added mock data channel
* Rewrote pc test to use mock classes & distinguishing the spies. 

TESTED: 
grunt test

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/113)

### CODE REVIEW

**Comment by trevj** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113)



---

Wow, thanks for looking at this. I think the test looks a lot better. I reviewed this pretty thoroughly and nitpickily because we'll all be looking at these objects a *lot* during the time to come.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 8 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPLvYDiVo9EioXcYTi)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L8)):</sup>
That we've found this useful would be useful feedback to freedomjs (TL;DR: method names of the form `onEventName` would be much much easier to mock).

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 12 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMApOuMaX84Ls3Bac)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L12)):</sup>
Return type here, and throughout.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 17 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMPw4mcQiuZnK83ZY)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L17)):</sup>
I think this should be private.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMUmAJ5NIv7rip6lW)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L24)):</sup>
style: space after the comma

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPNs2gakT1OpaSQKNO)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L24)):</sup>
Let's use more descriptive variable names throughout.

I would suggest:
```typescript
public on(eventName:string, callback:Function)
```

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 27 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMYEJWtrWEz8QsBbX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L27)):</sup>
Blank line between functions.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 30 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPNbvBPJfWpuIuN4zh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L30)):</sup>
This is useful but it would be better to provide a link to the freedomjs event handler docs, if any exists.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 37 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPN5cn63RKwHXElXsh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L37)):</sup>
I'm torn on this name. It's good to have `fake` in there since it highlights that this is a testing-only function but I feel it's a little clumsy...

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOXn0isx96S2nwuML)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
So, in `mock-freedom-in-module-env.ts` this type of object is called a `Skeleton`.

I think we should be consistent (and if we think these helpers will gradually accumulate behaviour and should actually just be called mocks, so be it).

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPPgtpgpIK0EE9O8ze)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
An aside, but important: will the TypeScript fail if `MockFreedomRtcDataChannel` does not actually fully implement the interface?

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOdsDCOoozc5KkgTR)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L21)):</sup>
Doesn't TypeScript have a notion of a default constructor?

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOnqvAX9xUY1zb8r5)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L31)):</sup>
Looks like a typo.

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 14 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQCgrtpftfQLseF4k)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L14)):</sup>
Did you think about making this inherit from `MockFreedomEventHandler`?

(I think inheritance is almost always a bad idea but just to raise the possibility.)

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 15 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQ3OyYnQ-5aeaTevX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L15)):</sup>
Tests or not, public fields are almost always a bad idea.

Since you're implementing `on` and `once`, it doesn't need to be public.

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQRLPa_cUkCAaXQBu)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L21)):</sup>
Again, does TypeScript have a default constructor?

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPPzbnODMs7fEVXsch)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L24)):</sup>
What about `off`?

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQWIam-VKiVie173d)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L36)):</sup>
style: spaces between functions

---

<sup>**[src/webrtc/peerconnection.spec.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPP1xZifiIGAg1w0VX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/webrtc/peerconnection.spec.ts#L31)):</sup>
If you're going to make this a sentence, let's add a full stop (personally I prefer sentence fragments but whatever).

---

<sup>**[src/webrtc/peerconnection.spec.ts, line 39 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPP9YSuX1WuO8BmyLV)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/webrtc/peerconnection.spec.ts#L39)):</sup>
style: use single quotes

---

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113)



---

Thanks! done. PTAL

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 8 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPLvYDiVo9EioXcYTi)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L8)):</sup>
Good idea, started doc: https://docs.google.com/document/d/1VnvDzcIQjOs5o9wm--qR_5pAuC-xthY7zpzMtKOui0Q/edit#

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 12 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMApOuMaX84Ls3Bac)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L12)):</sup>
yes! done.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 17 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMPw4mcQiuZnK83ZY)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L17)):</sup>
done.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMUmAJ5NIv7rip6lW)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L24)):</sup>
Done.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPNs2gakT1OpaSQKNO)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L24)):</sup>
Done.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 27 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMYEJWtrWEz8QsBbX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L27)):</sup>
Done.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 30 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPNbvBPJfWpuIuN4zh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L30)):</sup>
I'll leave the comment in. It's unclear to me if a URL is more or less stable than the comment here. :) 

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 37 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPN5cn63RKwHXElXsh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L37)):</sup>
Better verbose and clear than concise and unclear... it could be just `fakeEvent` (but I find that a more confusing), or `handleFakeEvent` ?

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOXn0isx96S2nwuML)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
OK, then I'll call them all Mocks. 

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPPgtpgpIK0EE9O8ze)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
yes.

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOdsDCOoozc5KkgTR)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L21)):</sup>
good point. :) removed/done.

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOnqvAX9xUY1zb8r5)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L31)):</sup>
Done.

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 14 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQCgrtpftfQLseF4k)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L14)):</sup>
yeah, I ummed and or'd on it. In the end decided it was a bit more explicit and somehow abstractly good to not do inheritance here. But I could (easily) be persuaded otherwise. 

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 15 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQ3OyYnQ-5aeaTevX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L15)):</sup>
I think you do want it to be public because it gives access to the event raising function. I would write a stub for that, but then I'd rather just use inheritance. 

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQRLPa_cUkCAaXQBu)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L21)):</sup>
Done.

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPPzbnODMs7fEVXsch)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L24)):</sup>
oh yeah... ok, that tips me over the edge... inheritance time. 

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQWIam-VKiVie173d)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L36)):</sup>
done, and standardized style with other file. 

---

<sup>**[src/webrtc/peerconnection.spec.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPP1xZifiIGAg1w0VX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/webrtc/peerconnection.spec.ts#L31)):</sup>
Just made it consistent with other tests w.r.t. initial capital. Other tests don't have a full stop, so will leave as is I think. 

---

<sup>**[src/webrtc/peerconnection.spec.ts, line 39 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPP9YSuX1WuO8BmyLV)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/webrtc/peerconnection.spec.ts#L39)):</sup>
Done. (and done below & in other files; where do those pesky double-quotes even come from?)

---

**Comment by trevj** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113)



---

Awesome. Many thanks for addressing all the comments.

:+1:

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 17 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMPw4mcQiuZnK83ZY)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L17)):</sup>
Actually, `eventTypes_` doesn't need to be a field at all, right?

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMUmAJ5NIv7rip6lW)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L24)):</sup>
style: `eventName`

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 32 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPNbvBPJfWpuIuN4zh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L32)):</sup>
Yeah, I agree :-/ I think the URL is helpful.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPN5cn63RKwHXElXsh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L42)):</sup>
I think the confusion arises from "fake" being both a noun and a verb, e.g. `sendSignal` would be unambigious.

Best I can think of right now is `emitEvent`. I don't feel very strongly though and if we can't think of a better name than that after all this time then it's probably as good as any other option :-)

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOXn0isx96S2nwuML)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
Awesome. Sorry, I know we went back and forth on this on the previous pull request too... Thanks.

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPPgtpgpIK0EE9O8ze)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
Great. Reason I asked is that you had the typo for `negotiated` and I guess this still compiled...

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 20 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPPzbnODMs7fEVXsch)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L20)):</sup>
Cool. Seems reasonable.

---

<sup>**[src/webrtc/peerconnection.spec.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPP1xZifiIGAg1w0VX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/webrtc/peerconnection.spec.ts#L31)):</sup>
I don't think we're consistent in our code! Might be a good addition to the style guide.

---

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113)



---

Thanks for comments! OK, now I think maybe it's ready... :) 

PTAL

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 17 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMPw4mcQiuZnK83ZY)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L17)):</sup>
good point. done.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 24 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPMUmAJ5NIv7rip6lW)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L24)):</sup>
Done.

---

<sup>**[src/freedom/mocks/mock-eventhandler.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPN5cn63RKwHXElXsh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-eventhandler.ts#L42)):</sup>
ok, after a little more thought I think the best name is maybe `handleEvent`. 

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPOXn0isx96S2nwuML)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
cool. :) 

---

<sup>**[src/freedom/mocks/mock-rtcdatachannel.ts, line 16 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPPgtpgpIK0EE9O8ze)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcdatachannel.ts#L16)):</sup>
hehe, yeah, would make any sane person wonder... answer is that I previously had both the correctly spelled version and a copied misspelling :) Having extra methods won't stop you satisfying the interface specification, only if you're missing stuff will it complain. 

---

<sup>**[src/freedom/mocks/mock-rtcpeerconnection.ts, line 14 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPQCgrtpftfQLseF4k)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/freedom/mocks/mock-rtcpeerconnection.ts#L14)):</sup>
As you can see I did end up going with the inheritance style here. :)

---

<sup>**[src/webrtc/peerconnection.spec.ts, line 31 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113#-JhPP1xZifiIGAg1w0VX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/2da42546f8ee7864872dbf4f7c71d28cc36b7ab2/src/webrtc/peerconnection.spec.ts#L31)):</sup>
Done.

---

**Comment by trevj** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/113)



---

Many thanks. :+1:

---

**Pull request merged**
