### PR TITLE
Added an arithmetic coder and some simple tests

### PR DESCRIPTION
**Pull request by blanu**
Added an arithmetic coder, specifically a range coder.
Added some simple tests using a uniform probability distribution.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/294)

### CODE REVIEW

**Comment by trevj** [comment]
Wow! Okay. I don't know much about arithmetic encoding but I like the tests and just have some code-level suggestions and comments.

---

Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 5 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqkz5lhCmIt9oOAGdX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L5)):</sup>
alphabetical ordering :-)

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 10 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzql4Jv40wctfSh3HDT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L10)):</sup>
spacing between operators

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqpn-aG-Hzy6_tS9H3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L11)):</sup>
will this work in every browser? it may be safer to `push` the values

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 18 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqlSo8s-cBCSvZUWeF)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L18)):</sup>
it's fine for this simple case but you're repeating the values in the title...i find names like `simple encode` and `simple decode` useful for these trivial cases

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqlmFmfDav5NgD0YLS)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L21)):</sup>
you repeat this line several times, how about extracting `encoder` and `decoder` into `describe`-level "member level" variables?

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqm8Khdh1RPGRVBoBa)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L36)):</sup>
did you take these values from some reference implementation?

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 6 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqq-RsHIibsjbyFdUR)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L6)):</sup>
great to include links!

did you base this code on some reference implementation?

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqmV3KHS1Ev8fMGc9D)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L29)):</sup>
Looks like we can use `Math.max` in ES6 -- see the top answer here:
http://stackoverflow.com/questions/1669190/javascript-min-max-array-values

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 41 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqq6pMHDQrwpXe4oH9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L41)):</sup>
Ditto, hopefully we can use `...` from ES6 here.

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 52 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqmebqrrj4uENN3RfZ)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L52)):</sup>
this looks like a perfect candidate for `forEach`

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 68 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqmvnlB-LE2ht5-iZ3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L68)):</sup>
i think you should raise an error if `items[index]` is out of range?

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 103 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqn6x7W2JLD05oMGt0)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L103)):</sup>
yay const!

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 158 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqqLU8XGpCt3T8mOp6)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L158)):</sup>
can you use the `protected` constructor trick here to prevent anybody creating an instance of `Coder`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294)

**Comment by blanu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 12 unresolved discussions, some commit checks pending.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 5 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqkz5lhCmIt9oOAGdX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L5)):</sup>
These are already in alphabetical order.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 10 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzql4Jv40wctfSh3HDT)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L10)):</sup>
Okay I have made this change.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 11 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqpn-aG-Hzy6_tS9H3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L11)):</sup>
Okay I have made this change.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqlmFmfDav5NgD0YLS)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L21)):</sup>
Since the encoder and decoder objects are stateful, I think you need to make a new instance for every test to be safe.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 36 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqm8Khdh1RPGRVBoBa)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L36)):</sup>
The encoding input is a real observed WebRTC packet that was breaking the encoder. The output is the encoding of that packet using a reference implementation. I have added comments to the test to say where the inputs and outputs come from.

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 0 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqmV3KHS1Ev8fMGc9D)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L0)):</sup>
Okay I have made this change.

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 0 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqqLU8XGpCt3T8mOp6)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L0)):</sup>
It looks like not: "arithmetic.ts(146,3): error TS1089: 'protected' modifier cannot appear on a constructor declaration."

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 0 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqmebqrrj4uENN3RfZ)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L0)):</sup>
I rewrote this using map.

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 0 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqq6pMHDQrwpXe4oH9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L0)):</sup>
I rewrote this using reduce.

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 0 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqq-RsHIibsjbyFdUR)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L0)):</sup>
There is no specific reference implementation for the code. There was psuedocode in http://www.arturocampos.com/ac_range.html that gave a general. However, it was incomplete and I filled in the gaps by looking at the other papers. 

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 0 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqmvnlB-LE2ht5-iZ3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L0)):</sup>
Okay I have made this change.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294)

**Comment by trevj** [comment]
Great work!

:+1:

---

Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 5 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqkz5lhCmIt9oOAGdX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L5)):</sup>
Gah, sorry.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 18 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqlSo8s-cBCSvZUWeF)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L18)):</sup>
Thanks!

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 23 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqlmFmfDav5NgD0YLS)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L23)):</sup>
In that case a `beforeEach` will help make things clearer:
http://jasmine.github.io/2.0/introduction.html#section-Setup_and_Teardown

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 6 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqq-RsHIibsjbyFdUR)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L6)):</sup>
Awesome.

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 29 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-Jzqq6pMHDQrwpXe4oH9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L29)):</sup>
Great! Sorry, I incorrectly assumed there was a `Math.sum`.

---

<sup>**[src/fancy-transformers/arithmetic.ts, line 147 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqqLU8XGpCt3T8mOp6)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.ts#L147)):</sup>
Oh, TypeScript.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294)

**Comment by blanu** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/fancy-transformers/arithmetic.spec.ts, line 21 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294#-JzqlmFmfDav5NgD0YLS)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/f1ea3f13cdc6db4787081ec9cd5791c794d8f40c/src/fancy-transformers/arithmetic.spec.ts#L21)):</sup>
Okay I have made this change.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/294)

**Pull request merged**
