### PR TITLE
add an NPM version badge

### PR DESCRIPTION
**Pull request by trevj**
Badges are fun and easy. I kinda like this one.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/333)

### CODE REVIEW

**Comment by jab** [comment]
Cool, hadn't come across fury.io. FWIW, if you want to use shields.io for this (more of a 1-stop shop for badges) you can use: https://img.shields.io/npm/v/uproxy-lib.svg

You can also use the shields.io shippable badge so that it matches the other badges better:
https://img.shields.io/shippable/54c823bf5ab6cc135289fbd8.svg

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/333#-:-K58ddtF7lTVa47u2dgU:636677995)*

**Comment by trevj** [comment]
Oh! Thanks, I love the shields.io badges. They make the markup nicer, too.

**Comment by jab** [comment]
nice :)

**Comment by trevj** [comment]
:+1:? :-)

**Comment by jab** [comment]
Big time! :) (Shippable failure has nothing to do with this/shouldn't block merging yeah?)

**Comment by trevj** [comment]
OK I updated, preserving the links and with a sane commit history.

**Pull request merged**
