### PR TITLE
better error handling and logging for cloud

### PR DESCRIPTION
**Pull request by trevj**
A bunch of stuff which, from tesing on my workstation and laptop, seems to significantly help the connection rate:
- factor out a class, `LineFeeder`, to convert an `ArrayBuffer` queue -> strings, delimiting on newlines (this was a real mess...#1 fix here)
- moar zork logging!
- always reject promises with an `Error`
- return after rejecting, when necessary

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/332)

### CODE REVIEW

**Comment by trevj** [comment]
Anecdotally, it *seems* to help with this issue but I can't really be sure yet:
https://github.com/uProxy/uproxy/issues/2115

**Comment by lucyhe** [comment]
looking great!!

---

Reviewed 5 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/zork/freedom-module.ts, line 79 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/332#-K52efix20xSmwC5qA1u:-K52efix20xSmwC5qA1v:-957293554) ([raw file](https://github.com/uproxy/uproxy-lib/blob/4f367c39f500c745c4f572dfd6c40b8129feeda4/src/zork/freedom-module.ts#L79)):*
nit: more descriptive function name

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/332#-:-K52qJBqGwb9HR-SSWgj:-1765186165)*

**Comment by trevj** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/zork/freedom-module.ts, line 79 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/332#-K52efix20xSmwC5qA1u:-K57JtNIjrGOb9cye2RP:-1013429418) ([raw file](https://github.com/uproxy/uproxy-lib/blob/4f367c39f500c745c4f572dfd6c40b8129feeda4/src/zork/freedom-module.ts#L79)):*
Quite right! It wasn't even camelcase. Renamed to `processCommand`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/332)*

**Comment by lucyhe** [comment]
:+1: !

**Pull request merged**
