### PR TITLE
Use actual local interfaces in the mirror candidates.

### PR DESCRIPTION
**Pull request by bemasc**
Windows does not allow physical interfaces to send to loopback.
Fixes https://github.com/uProxy/uproxy/issues/1740

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/231)

### CODE REVIEW

**Comment by iislucas** [comment]
The restructuring looks good, methods are doing things that more closely correspond to their description. 

Just a couple of requests for comments to explain some call ordering constraints. Trusting you to add those. Then big fat LGTM :+1: as I'm very happy to see this land and fix windows! :)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 313 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFBDnZqk4ADAMwpLI-)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn-pipe/churn-pipe.ts#L313)):</sup>
So not part of this pull request, but rather close to it... the type of "promises" doesn't seem to be used, so it should be Object instead of "any"... 

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 380 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFDAwUzKDnaA9lPq2D)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn-pipe/churn-pipe.ts#L380)):</sup>
So it seems that bindLocal_ is required to have been called before this method, this should be written in a comment for the method. Also, I don't quite see how/why this is enforced. Maybe add that as a comment too? 

---

<sup>**[src/churn/churn.ts, line 173 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFELE-_JC0T-g83gFt)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn/churn.ts#L173)):</sup>
Should this comment be a line lower down?

---

<sup>**[src/churn/churn.ts, line 196 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFEaYG42PXZGUnEW7t)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn/churn.ts#L196)):</sup>
Seems like a slightly random place for this comment?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231)

**Comment by iislucas** [comment]
(assigned to me as @trevj is out until tomorrow)

**Comment by bemasc** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 313 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFBDnZqk4ADAMwpLI-)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn-pipe/churn-pipe.ts#L313)):</sup>
Done.

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 380 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFDAwUzKDnaA9lPq2D)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn-pipe/churn-pipe.ts#L380)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 173 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFELE-_JC0T-g83gFt)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn/churn.ts#L173)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 196 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231#-JvFEaYG42PXZGUnEW7t)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/3d09acdda5e32c17370f03a879a7bf54c35d083b/src/churn/churn.ts#L196)):</sup>
Moved.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231)

**Comment by iislucas** [comment]
:+1: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/231)

**Pull request merged**
