### PR TITLE
Ensure that DataChannel does not miss an initial incoming message.

### PR DESCRIPTION
**Pull request by bemasc**
This problem is analogous to https://github.com/freedomjs/freedom/issues/251

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/154)

### CODE REVIEW

**Comment by trevj** [comment]
Cool!

---





<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
I haven't seen this before, is it equivalent to a default value?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by bemasc** [comment]
<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
Yes.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by trevj** [comment]
<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
The asynchronous block at line 136 looks funny, then -- shouldn't that be part of the static constructor?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by bemasc** [comment]
<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
I'm not sure I understand.  Are you suggesting to add a method like `DataChannelClass.updateLabel()`?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by trevj** [comment]
<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
No, but this looks like async work that needs to happen before the object is ready for use. Didn't you add `createFromRtcDataChannel` for exactly this kind of thing?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by bemasc** [comment]
<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
You added `createFromRtcDataChannel` :).

Yes, unfortunately, we have a conflict between needing to call the constructor synchronously (to register the event listeners) and some aspects not being ready synchronously (like the label).  This code actually will not return the object before it is ready, due to freedom message sequencing guarantees, but we can make it more explicit if you like, for example by adding a new method like `updateLabel()`, or a new attribute like `onceReady`, etc.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by trevj** [comment]
<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
You added the static constructor!:
https://github.com/uProxy/uproxy-lib/commit/af950daa43ddf00695030fa2d3856822c7e22fe3#diff-a83218584d1f7afd1ded1688d5a23da9

Seems like the `getLabel` call can just go in `createFromRtcDataChannel`.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by bemasc** [comment]
<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
Done.  This required adding a `DataChannelClass.setLabel()` method.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Comment by trevj** [comment]
:+1:

---





<sup>**[src/webrtc/datachannel.ts, line 130 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154#-JmsNk2czM_QXO0zv1GN)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/d7fb06d62f97b2c9b0a3fb7c6f1cba24dfa14a87/src/webrtc/datachannel.ts#L130)):</sup>
So be it :-) Thanks.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/154)

**Pull request merged**
