### PR TITLE
Introduce Active Queue Management

### PR DESCRIPTION
**Pull request by bemasc**
This is effectively a CPU adaptation mechanism, slowing down the browser's transfer rate when it begins to overwhelm the CPU.  In testing, this appears to improve the reliability and responsiveness of the proxy when throughput becomes CPU limited.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/276)

### CODE REVIEW

**Comment by trevj** [comment]
Awesome. I haven't had a chance to examine the code yet but here is a comparison of throughput with this pull request vs. without:

=== with

with

=== without

without

Doesn't look too bad, right?

**Comment by trevj** [comment]
Sorry, not just awesome. *Seriously* awesome.

**Comment by trevj** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[src/aqm/aqm.ts, line 10 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIk7d4QUw13poqz9G9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L10)):</sup>
OK, I see two problems here:
 1. not all AQMs need a traced/fast send
 1. there's a bunch of public fields and functions

I think if you change the constructors of the implementations to:
 1. accept a send/fast send/traced send (as appropriate) callbacks
 1. accept a tracing fraction, if applicable
then you can avoid the need for any public fields, make your AQMs near-immutable, and can reasonably-significantly shorten this file.

---

<sup>**[src/aqm/aqm.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIiz7--M9PH3gxpZs9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L28)):</sup>
What is the meaning of the return type?

---

<sup>**[src/aqm/aqm.ts, line 65 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIo98_KEjYtohvkB5u)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L65)):</sup>
If you *really* need these comments, then your file is too long! (I don't think it is, BTW, so I don't think you need these)

---

<sup>**[src/aqm/aqm.ts, line 213 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIoOxVjv6LblVSKCbX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L213)):</sup>
What should happen if `tracedSender` throws?

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 444 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyImCs0Gp0qXSf-GKoK)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/churn-pipe/churn-pipe.ts#L444)):</sup>
Quibble: I don't think you would ever call a plain old send method `sender`, so `fastSend_` and `tracedSend_` might be better.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276)

**Comment by bemasc** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[src/aqm/aqm.ts, line 10 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIk7d4QUw13poqz9G9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L10)):</sup>
Done.

---

<sup>**[src/aqm/aqm.ts, line 28 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIiz7--M9PH3gxpZs9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L28)):</sup>
Added a comment: "Returns true if the packet was sent, or false if it was dropped."

---

<sup>**[src/aqm/aqm.ts, line 65 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIo98_KEjYtohvkB5u)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L65)):</sup>
Removed

---

<sup>**[src/aqm/aqm.ts, line 213 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIoOxVjv6LblVSKCbX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L213)):</sup>
I have no idea :)

---

<sup>**[src/churn-pipe/churn-pipe.ts, line 444 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyImCs0Gp0qXSf-GKoK)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/churn-pipe/churn-pipe.ts#L444)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276)

**Comment by trevj** [comment]
Awesome. I would add one warning, then :100: .

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/aqm/aqm.ts, line 194 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIoOxVjv6LblVSKCbX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L194)):</sup>
Then a warning is probably appropriate.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276)

**Comment by bemasc** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/aqm/aqm.ts, line 213 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276#-JyIoOxVjv6LblVSKCbX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/8d55cb24e9b2f70364a269b36afbb3592eda4b21/src/aqm/aqm.ts#L213)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/276)

**Pull request merged**
