### PR TITLE
Added port control module to uproxy-lib

### PR DESCRIPTION
**Pull request by kennysong**
We now try to use NAT-PMP, PCP, and UPnP to open ports when making a connection inside churn.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/222)

### CODE REVIEW

**Comment by bemasc** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/churn/churn.ts, line 222 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CzNLi2ITKs53Vsl1)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/src/churn/churn.ts#L222)):</sup>
spaces around "*".  Might be worth defining a variable.

---

<sup>**[src/churn/churn.ts, line 225 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CJvPs5V3RAkulP3Z)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/src/churn/churn.ts#L225)):</sup>
I think you want "log.debug"

---

<sup>**[third_party/freedom-typings/port-control.d.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CrUYkK46jERGqsGe)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/third_party/freedom-typings/port-control.d.ts#L42)):</sup>
Nit: extra spaces.

---

<sup>**[third_party/freedom-typings/port-control.d.ts, line 47 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CuYc_Ivl_wUCfK-Q)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/third_party/freedom-typings/port-control.d.ts#L47)):</sup>
Need a blank line

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222)

**Comment by kennysong** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn/churn.ts, line 222 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CzNLi2ITKs53Vsl1)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/src/churn/churn.ts#L222)):</sup>
Done.

---

<sup>**[src/churn/churn.ts, line 225 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CJvPs5V3RAkulP3Z)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/src/churn/churn.ts#L225)):</sup>
Done.

---

<sup>**[third_party/freedom-typings/port-control.d.ts, line 42 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CrUYkK46jERGqsGe)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/third_party/freedom-typings/port-control.d.ts#L42)):</sup>
Done.

---

<sup>**[third_party/freedom-typings/port-control.d.ts, line 47 \[r1\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-Ju9CuYc_Ivl_wUCfK-Q)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/c82cf76030cff43ec13aa53eba06cdc376751e9c/third_party/freedom-typings/port-control.d.ts#L47)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222)

**Comment by bemasc** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn/churn.ts, line 228 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-JuCiFOb38b_iBcmVKLh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/bded9f7ff72f3eff449014e6409e9605b2434ba5/src/churn/churn.ts#L228)):</sup>
Does this work?  I think you need a %1 in the string?

---

<sup>**[third_party/freedom-typings/port-control.d.ts, line 27 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-JuCiPvl_oN7ZvYqnQE_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/bded9f7ff72f3eff449014e6409e9605b2434ba5/third_party/freedom-typings/port-control.d.ts#L27)):</sup>
Nit: no space between `:` and `number` in function declarations.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222)

**Comment by bemasc** [comment]
This is basically good to go except that the freedom module itself needs to be reviewed first.

---

Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222)

**Comment by kennysong** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[src/churn/churn.ts, line 228 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-JuCiFOb38b_iBcmVKLh)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/bded9f7ff72f3eff449014e6409e9605b2434ba5/src/churn/churn.ts#L228)):</sup>
This works – `log.debug` takes a rest parameter.

---

<sup>**[third_party/freedom-typings/port-control.d.ts, line 27 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222#-JuCiPvl_oN7ZvYqnQE_)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/bded9f7ff72f3eff449014e6409e9605b2434ba5/third_party/freedom-typings/port-control.d.ts#L27)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/222)

**Comment by bemasc** [comment]
:+1:

**Pull request merged**
