### PR TITLE
replace ancient Sublime config and add instructions to the README

### PR DESCRIPTION
**Pull request by trevj**
@jab, figured you might be interested in this pull request which replaces our ancient Sublime config and describes how to get syntax highlighting, "jump to definition", and more in Sublime.

Do you think the entry in the README is clear, necessary, and in the correct place?

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/330)

### CODE REVIEW

**Comment by jab** [comment]
Hey @trevj, this looks great! Do you think it's worth adding a .editorconfig while we're at it? (can be a separate PR.) I use it in my own projects and would recommend. http://editorconfig.org/

In that vein, [pre-commit](http://pre-commit.com/) can also be nice along with a pre-commit hook that runs a code formatter to help new contributors' code comply with any style guidelines we have.

(And sorry again I missed this till now. Transient notifications hiccup. Fixed now.)

**Comment by trevj** [comment]
No worries, @jab!

I haven't come across `.editorconfig` but if you recommend it I'd be interested, *especially* if it can help with a code formatting pre-submit check, for which we've had an issue open forever (I just added a comment):
https://github.com/uProxy/uproxy/issues/79

BTW, I'd be interested in how you fixed your notifications process because team members seem to keep missing pull requests.

**Comment by jab** [comment]
(it's pre-commit that could help with a code formatting pre-commit hook; .editorconfig just makes it so anyone with the editorconfig plugin installed for their editor will automatically have their editor configured with our settings, e.g. for indent size, tabs vs. spaces, etc.)

Is there a code formatter you know and like already? I didn't immediately see one for js/ts listed under http://pre-commit.com/hooks.html (could have missed it), but if not it'd still be straightforward to get this set up.

My notifications hiccup was due to a misconfigured email filter, so probably not the same issue others are having?

**Comment by bemasc** [comment]
> Is there a code formatter you know and like already?

Maybe tslint: https://github.com/uProxy/uproxy/issues/537

**Comment by trevj** [comment]
Right, seems like `.editorconfig` could help get everyone's code in the right state for a presubmit check which would be great.

**Comment by trevj** [comment]
Looks like clang-format now also supports TypeScript:
http://probst.io/blog/2015/04/11/clang-format-is-available-via-npm/

No idea on the relative merits of each...

**Pull request merged**
