### PR TITLE
merge in uproxy-networking code

### PR DESCRIPTION
**Pull request by trevj**
This copies across all code from the [uproxy-networking repository](https://github.com/uProxy/uproxy-networking) into this one, with the intention of deleting that repository and associated NPM. Fixes:
https://github.com/uProxy/uproxy/issues/1421

I tried to copy as much as possible, with the following exceptions:
- update paths, in code and JSON files
- workaround TypeScript compiler errors owing to latest es6-promise definitions
- fix some sample apps that had atrophied, viz. Simple TURN, and churn sample apps

This is a huge diff so you might prefer to patch this in and perform a diff locally; I prefer `meld` and if your system is anything like mind you can execute a command similar to this one to highlight the changes in this pull request:

``` bash
meld ~/src/uproxy-networking ~/src/uproxy-lib
```

The code is copied at commit (ce0efe8)[https://github.com/uProxy/uproxy-networking/commit/ce0efe8ae8e9e506b0e13a41c30438866ce59c78], which means the following pull requests are outstanding:
- ~~https://github.com/uProxy/uproxy-networking/pull/257~~
- https://github.com/uProxy/uproxy-networking/pull/255
- ~~https://github.com/uProxy/uproxy-networking/pull/245~~
- ~~https://github.com/uProxy/uproxy-networking/pull/226~~
- https://github.com/uProxy/uproxy-networking/pull/210
- ~~https://github.com/uProxy/uproxy-networking/pull/259~~
- ~~https://github.com/uProxy/uproxy-networking/pull/258~~

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/166)

### CODE REVIEW

**Comment by iislucas** [comment]
This is great! 
Can you merge in/update the README also?

**Comment by trevj** [comment]
I just updated the README. I wanted to see if Travis and Shippable were happy yet :-)

@bemasc offered to review but if you can also take a look, by all means.

**Comment by trevj** [comment]
Also, I should say that I'm happy to copy across any subsequent changes to uproxy-networking.

**Comment by trevj** [comment]
Update: I will try this with uProxy before going any further.

**Comment by trevj** [comment]
I just tried this with uProxy and it was straightforward to migrate:
https://github.com/uProxy/uproxy/compare/trevj-no-more-uproxy-networking

**Comment by trevj** [comment]
Keeping this open until all outstanding pull requests are copied across.

**Pull request merged**
