### PR TITLE
Make DataChannel.getBufferedAmount() include all pending data.

### PR DESCRIPTION
**Pull request by bemasc**
Not really tested... but at least it builds and the existing tests pass.

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/130)

### CODE REVIEW

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130)



---

This seems to change the semantics of getBufferedAmount is a way that I think is might not be as good as it can be... I think we are better to have two metrics: one for the size of stuff on `this.toPeerDataQueue_` and one for the usrsctp stack (the current 'getBufferedAmount'). Otherwise we're going to confuse ourself about what's on which bit of queuing stack. Make sense?

---

**Comment by bemasc** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130)



---

Actually, neither of these measures include the usrsctp output buffer!  The current return value is the length of a queue in the browser that precedes usrsctp.

My view is that this class is an abstraction layer, and should hide these distinctions.

---

**Comment by trevj** [comment]
I agree with @iislucas that there's something not quite right about collapsing the two values; if this is something callers really need, I'd be happy if it were added as a separate method (I guess this is what @iislucas is proposing too).

**Comment by bemasc** [comment]
OK ... I've split the method in two.  I've renamed them both, which is safe because `getBufferedAmount` was not used anywhere.  PTAL.

I don't see what `getBrowserBufferedAmount` is useful for, but I suppose it's not expensive to keep it.

**Comment by trevj** [comment]
I don't see why it's useful either! Why did you want to add this? :-)

**Comment by iislucas** [comment]
OK, I think this is good; provides the basis for the instrumentation we want :+1:  from me. @trevj  ?

**Comment by trevj** [comment]
Sure, :+1: . You probably want to do some version number bumping, too.

**Comment by bemasc** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130)



---

OK, I've changed getTotalBufferedAmount to getJavascriptBufferedAmount, which I think is what you really wanted anyway.  PTAL.

I didn't bump package.json because we're not cutting releases from dev branch anyway.

---

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130)

Reviewed files:
- src/webrtc/datachannel.ts @ r7

---

Even better! :+1: :+1: 

One nit on a TODO comment. 

---

<sup>**[src/webrtc/datachannel.ts, line 97 \[r7\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130#-JjXQt0LzxL4J9NbI1w3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/a564a25dea79ef4ee78a931a35d1ab49c2f71800/src/webrtc/datachannel.ts#L97)):</sup>
This seems to be done below. Remote comment? or clarify you want to do it in a more accurate way? (I was pretty sure JS strings are always 2 bytes... so I think you've got it right)

---

**Comment by bemasc** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130)







---

<sup>**[src/webrtc/datachannel.ts, line 97 \[r7\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130#-JjXQt0LzxL4J9NbI1w3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/a564a25dea79ef4ee78a931a35d1ab49c2f71800/src/webrtc/datachannel.ts#L97)):</sup>
Nope and sort-of.

`toPeerDataBytes_` only includes bytes in arraybuffers.  Strings are not counted.

Javascript uses UTF-16 (two bytes per character) to store strings ([except when it doesn't](https://blog.mozilla.org/javascript/2014/07/21/slimmer-and-faster-javascript-strings-in-firefox/)) ... but data channels use UTF-8 to send strings, and they are automatically converted by the sending and receiving browsers.

I wasn't sure what to do with this situation (what is `toPeerDataBytes_` counting anyway...), so since we don't make any intensive use of strings, I just left them out.  Suggestions welcome.

---

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130)







---

<sup>**[src/webrtc/datachannel.ts, line 97 \[r7\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/130#-JjXQt0LzxL4J9NbI1w3)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/a564a25dea79ef4ee78a931a35d1ab49c2f71800/src/webrtc/datachannel.ts#L97)):</sup>
I see; meh... OK, all good. :+1:

---

**Pull request merged**
