### PR TITLE
Updated dependent package versions and other maintenance

### PR DESCRIPTION
**Pull request by iislucas**
- Updated all out of date package dependencies to latest versions.
- es6-promise v2 requires an explicit call to `polyfill()`
- Moved all creation of `build/third_party` into `./setup.sh third_party` (nothing inside gruntfile now)
- Separated coverage reports so that debugging unit tests is more reasonable: 
  - coverage gets run by shippable (target `unit_test_coverage`)
  - default for debugging tests is `unit_test_debug` (`grunt test` does this)
- Improved names of some internal variable names/build target rules
- `.npmignore` doesn't ignore src and build/dev so that we can support working development repos with github src links
- Unit tests now catch rejected promises. 
- Fixed `.d.ts` output and ignoring to avoid silly compile errors about mixed core/module environments. 
- Added shippable re-enable our shippable CI tests for uproxy-lib

TESTED: 
- `grunt clean && grunt test` (checked tests passed)
- `grunt clean && grunt unit_test_coverage` (checked produced coverage reports)
- `grunt clean && grunt dist` (checked the populated dist dir)
- Manually ran sample apps. 

[Review on Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/138)

### CODE REVIEW

**Comment by iislucas** [comment]
@trevj Can you have a look? Thanks!

**Comment by trevj** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138)



---

Generally this looks good but there's a lot going on here! I think you could have split this into smaller pull requests.

Happy to see this improving though (and the move to `es6-promise` 2.x.x).

---

<sup>**[.travis.yml, line 2 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3EUfx_goCv9jC1BWE)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/.travis.yml#L2)):</sup>
is node 11 flaky? i've been using node 12 on my macbook...

---

<sup>**[.travis.yml, line 9 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3FEd01PX7wRxHz3X-)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/.travis.yml#L9)):</sup>
I don't quite see what you're trying to do with this change in conjunction with the change to `test` in `package.json`.

Ultimately, I think you want Travis to run `grunt unit_test_debug`, right?

---

<sup>**[Gruntfile.coffee, line 60 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DRvb7L05qqcoAuix)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/Gruntfile.coffee#L60)):</sup>
How about just `unit_test`? ("it's cleaner")

---

<sup>**[Gruntfile.coffee, line 72 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DX08haA65DSXPBl9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/Gruntfile.coffee#L72)):</sup>
How about just `coverage`? The prefix is an implementation detail.

---

<sup>**[Gruntfile.coffee, line 197 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DjjFp0p5lwCHo--G)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/Gruntfile.coffee#L197)):</sup>
You might consider co-locating the `xxx` and `xxxCov` lines, to make it easier to grok when one or the other is missing.

---

<sup>**[package.json, line 4 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DsSEGbD1jJGxCYRd)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L4)):</sup>
something not quite right here :-)

---

<sup>**[package.json, line 39 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3EhRLsqlSpDyiL3GX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L39)):</sup>
where is karma used?

---

<sup>**[package.json, line 44 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3El5ncR9FJufbkpCq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L44)):</sup>
this is weird.

---

<sup>**[setup.sh, line 40 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DzFXJUuWtS-HeMLn)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/setup.sh#L40)):</sup>
I think you need:
```bash
  runCmd "cd $ROOT_DIR"
```

---

<sup>**[setup.sh, line 69 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3BUQzdnrIL2z5wJvK)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/setup.sh#L69)):</sup>
nit: the comments on `install` and `third_party` aren't very helpful (which subset? all needed build files? no mention of `npm install`)

---

<sup>**[src/handler/queue.spec.ts, line 51 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3C9zpbOdpFmW2YLxB)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/src/handler/queue.spec.ts#L51)):</sup>
oh this is weird, the test doesn't fail without the catch block???

---

<sup>**[src/samples/simple-freedom-chat/freedom-module.ts, line 14 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3CHOqDveNEWn9m9Yz)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/src/samples/simple-freedom-chat/freedom-module.ts#L14)):</sup>
I'm curious why you export this?

---

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138)



---

Yeah, sorry about the number of things going on, it started off small, and then kind of grew a bit more than I meant it to.  I think they are separate w.r.t. code paths; but if you like I can break this into a couple of separate pull requests. But of course it would be easier (for me!) to do it in one go :) 

---

<sup>**[.travis.yml, line 2 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3EUfx_goCv9jC1BWE)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/.travis.yml#L2)):</sup>
Yes, they seemed to skip 0.11. Good point on node 12, I'll add that as we should be aiming for compatibility with it. 

---

<sup>**[.travis.yml, line 9 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3FEd01PX7wRxHz3X-)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/.travis.yml#L9)):</sup>
I ended up thinking it was best to build the whole distribution, including code overage as we'd like to get code coverage from our CI runs in the future. Only running unit tests means you don't produce code coverage. 

---

<sup>**[Gruntfile.coffee, line 60 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DRvb7L05qqcoAuix)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/Gruntfile.coffee#L60)):</sup>
done.

---

<sup>**[Gruntfile.coffee, line 72 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DX08haA65DSXPBl9)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/Gruntfile.coffee#L72)):</sup>
good point. 

---

<sup>**[Gruntfile.coffee, line 197 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DjjFp0p5lwCHo--G)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/Gruntfile.coffee#L197)):</sup>
good idea. Sorted by name now. 

---

<sup>**[package.json, line 4 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DsSEGbD1jJGxCYRd)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L4)):</sup>
:) fixed.

---

<sup>**[package.json, line 39 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3EhRLsqlSpDyiL3GX)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L39)):</sup>
oops, an experiment crept in. removed. Removed. 

---

<sup>**[package.json, line 44 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3El5ncR9FJufbkpCq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L44)):</sup>
should be dist. good catch. 

---

<sup>**[setup.sh, line 40 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3DzFXJUuWtS-HeMLn)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/setup.sh#L40)):</sup>
Done.

---

<sup>**[setup.sh, line 69 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3BUQzdnrIL2z5wJvK)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/setup.sh#L69)):</sup>
tried to clarify a bit, read better now? 

---

<sup>**[src/handler/queue.spec.ts, line 51 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3C9zpbOdpFmW2YLxB)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/src/handler/queue.spec.ts#L51)):</sup>
Correct, the test passes, but some JS runtimes produce console logs for errors for uncaught promise rejections. The catches here are to avoid those spurious logs. 

---

<sup>**[src/samples/simple-freedom-chat/freedom-module.ts, line 14 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3CHOqDveNEWn9m9Yz)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/src/samples/simple-freedom-chat/freedom-module.ts#L14)):</sup>
So that you can debug from a web-worker console. In browserify all objects are hidden unless exported. By exporting, we get access to them under the "standalone" option of the browserify rule (set to `browserify_exports` in our grunt rule)

---

**Comment by trevj** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138)



---

Sorry, didn't see the update to this. Well no need to break it into smaller pull requests now :-p

---

<sup>**[.travis.yml, line 10 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3FEd01PX7wRxHz3X-)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/.travis.yml#L10)):</sup>
You don't need code coverage on Travis, though, right?

It's not a very fast environment to begin with.

---

<sup>**[package.json, line 42 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3El5ncR9FJufbkpCq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L42)):</sup>
By default, Travis runs `npm test`. So I don't think you need to set a `script:` action in `.travis.yml`.

---

<sup>**[setup.sh, line 70 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3BUQzdnrIL2z5wJvK)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/setup.sh#L70)):</sup>
"installs the all the" -> "installs all the"

"This part of the" -> "this is part of the" ?

---

<sup>**[src/samples/simple-freedom-chat/freedom-module.ts, line 14 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3CHOqDveNEWn9m9Yz)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/src/samples/simple-freedom-chat/freedom-module.ts#L14)):</sup>
Cool. Wanna do this copypaste, too?

---

**Comment by trevj** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138)



---

:+1: once those last few things are fixed, BTW.

---

**Comment by iislucas** [comment]
Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138)







---

<sup>**[.travis.yml, line 10 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3FEd01PX7wRxHz3X-)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/.travis.yml#L10)):</sup>
Fair; just running unit tests now. 

---

<sup>**[package.json, line 42 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3El5ncR9FJufbkpCq)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/package.json#L42)):</sup>
Good point; I'll remove form here an leave in `.travis.yml`

---

<sup>**[setup.sh, line 70 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3BUQzdnrIL2z5wJvK)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/setup.sh#L70)):</sup>
Done.

---

<sup>**[src/samples/simple-freedom-chat/freedom-module.ts, line 14 \[r2\]](https://reviewable.io:443/reviews/uproxy/uproxy-lib/138#-Jk3CHOqDveNEWn9m9Yz)** ([raw file](https://github.com/uproxy/uproxy-lib/blob/7732805a6068f28508ae895767da91dc18df3026/src/samples/simple-freedom-chat/freedom-module.ts#L14)):</sup>
Done.

---

**Pull request merged**
