### PR TITLE
Allow inbound traffic from browser ports bound to the "ANY" interface.

### PR DESCRIPTION
**Pull request by bemasc**
Fixes https://github.com/uProxy/uproxy/issues/2334

---

This change is [Reviewable](https://reviewable.io/reviews/uproxy/uproxy-lib/378)

### CODE REVIEW

**Comment by trevj** [comment]
Excellent! :+1:

**Comment by bemasc** [comment]
Thanks!  Since I could never reproduce the issue, we might want to check it on your machine before committing.

**Comment by trevj** [comment]
Good idea! I'll do this when I'm back tomorrow.

**Comment by trevj** [comment]
It works! Yay! :+1:

**Pull request merged**
